ITEMS = [
    {
        "exchangeNo": "1",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "40",
        "iPackageId": "3406495",
        "sPackageId": "5476500",
        "sImg": "r.default",
        "sPackageName": "交易牌*2"
    },
    {
        "exchangeNo": "2",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "40",
        "iPackageId": "3406496",
        "sPackageId": "5476501",
        "sImg": "i.default",
        "sPackageName": "蕴含卢佩恩之光的货币箱子*2"
    },
    {
        "exchangeNo": "3",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "60",
        "iPackageId": "3406497",
        "sPackageId": "5476502",
        "sImg": "o.default",
        "sPackageName": "仙灵恢复药（绑定）*6"
    },
    {
        "exchangeNo": "4",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "30",
        "iPackageId": "3406500",
        "sPackageId": "5476505",
        "sImg": "a.default",
        "sPackageName": "跳跃精华*1"
    },
    {
        "exchangeNo": "5",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "40",
        "iPackageId": "3406498",
        "sPackageId": "5476503",
        "sImg": "s.default",
        "sPackageName": "[每日]艾芙娜委托完成券*6"
    },
    {
        "exchangeNo": "6",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "40",
        "iPackageId": "3406499",
        "sPackageId": "5476504",
        "sImg": "c.default",
        "sPackageName": "混沌地牢休息奖励恢复秘药[1]*1"
    },
    {
        "exchangeNo": "7",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "30",
        "iPackageId": "3406501",
        "sPackageId": "5476506",
        "sImg": "u.default",
        "sPackageName": "战斗道具综合箱子*5"
    },
    {
        "exchangeNo": "8",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "30",
        "iPackageId": "3406502",
        "sPackageId": "5476507",
        "sImg": "l.default",
        "sPackageName": "增益型战斗道具箱子*5"
    },
    {
        "exchangeNo": "9",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "25",
        "iPackageId": "3406503",
        "sPackageId": "5476508",
        "sImg": "f.default",
        "sPackageName": "传说~高级卡牌包2 *5"
    },
    {
        "exchangeNo": "10",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "10",
        "iPackageId": "3406504",
        "sPackageId": "5476509",
        "sImg": "d.default",
        "sPackageName": "[每周]艾芙娜委托+1*1"
    },
    {
        "exchangeNo": "11",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "25",
        "iPackageId": "3406505",
        "sPackageId": "5476510",
        "sImg": "p.default",
        "sPackageName": "新手生命气息恢复药水*5"
    },
    {
        "exchangeNo": "12",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "350",
        "iPackageId": "3406506",
        "sPackageId": "5476511",
        "sImg": "h.default",
        "sPackageName": "[活动]贝拉的祝福（14天）*1"
    },
    {
        "exchangeNo": "13",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "350",
        "iPackageId": "3406507",
        "sPackageId": "5476512",
        "sImg": "v.default",
        "sPackageName": "银币幸运箱子*5"
    },
    {
        "exchangeNo": "14",
        "dayLimit": "0",
        "weekLimit": "0",
        "monthLimit": "0",
        "allLimit": "0",
        "exchangeScore": "350",
        "iPackageId": "3406508",
        "sPackageId": "5476513",
        "sImg": "m.default",
        "sPackageName": "梅内里克之书*1"
    }
]
